macro(CopyFile SAMPLE_NAME FROM TO)
	add_custom_command(TARGET ${SAMPLE_NAME} PRE_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/${FROM}  ${CMAKE_CURRENT_BINARY_DIR}/${TO})
endmacro()
