macro(CustomCommandSample SAMPLE_NAME PYTHON_SCRIPT)
	add_custom_command(TARGET ${SAMPLE_NAME} PRE_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/${PYTHON_SCRIPT}.py ${CMAKE_CURRENT_BINARY_DIR}/${PYTHON_SCRIPT}.py)
	add_custom_command(TARGET ${SAMPLE_NAME} PRE_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_SOURCE_DIR}/../Utils/Visualizer.py ${CMAKE_CURRENT_BINARY_DIR}/Visualizer.py)
endmacro()